language: ruby
bundler_args: --without development
env: SECRET_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
rvm:
  - 2.1.0
before_script:
  - psql -c 'create database pairtrix_test;' -U postgres
  - bundle exec rake db:migrate
