language: ruby
bundler_args: --without development
env:
  - SECRET_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  - S3_KEY=key
  - S3_SECRET=secret
rvm:
  - 2.1.1
before_script:
  - psql -c 'create database pairtrix_test;' -U postgres
  - bundle exec rake db:migrate
