defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *defaults
  database: pairtrix_development

test: &test
  <<: *defaults
  database: pairtrix_test

cucumber:
  <<: *test

postgres:
  adapter: postgresql
  database: pairtrix_test
  username: postgres
